name: asn1lib
version: 2.0.0
description: An ASN1 parser library for Dart. Encodes / decodes from ASN1 Objects to BER bytes
homepage: https://github.com/wstrange/asn1lib
environment:
 sdk: ^3.0.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  parameterized_test: ^1.1.1
  test: ^1.22.0

# PEM certs are for testing - and are OK to publish
false_secrets:
 - /test/resource/*.pem
 - test/*.dart
